[workspace]
resolver = "2"
members = [
    # -- Application Libraries
    "crates/libs/base", # e.g., config, time, encoding, utilities.
    "crates/libs/core", # e.g., model/store, events (token/pwd).

    # -- Application Services
    "crates/services/web-server",

    # -- Tools
    "crates/tools/gen_key",
]
