[workspace]
resolver = "2"
members = [
    # -- Application Libraries
    "crates/libs/base", # e.g., base64, time.
    "crates/libs/core", # e.g., model/store, context, events, (token/pwd).

    # -- Application Services
    "crates/services/web-server",

    # -- Tools
    "crates/tools/gen_key",
]
