[package]
name = "gen-key"
version = "0.1.0"
edition = "2021"

[dependencies]
# -- App Crates
lib-base = { path = "../../../crates/libs/base"}
# -- Others
rand = "0.8"
anyhow = "1" # Ok for tools/



